<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Aria.Remote</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ARIA.Core\ARIA.Core.csproj" />
  </ItemGroup>
</Project>
