<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Aria.Remote</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ARIA.Remote.Tests" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="RemoteClient\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ARIA.Core\ARIA.Core.csproj" />
  </ItemGroup>
</Project>
