<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Aria.Audio</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ARIA.Core\ARIA.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\runtimes\**\native\*" CopyToOutputDirectory="PreserveNewest" Link="runtimes\%(RecursiveDir)%(Filename)%(Extension)" Visible="false" />
  </ItemGroup>
</Project>
